{
 "title": "Container Registry Health",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Actions</h1>"
   }
  },
  {
   "title": "Container Registry Pull Actions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticLogs\n| where ResourceId contains 'MICROSOFT.CONTAINERREGISTRY'\n| where OperationName == 'Pull'\n| where $__timeFilter(Timestamp)\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Container Registry Push Actions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticLogs\n| where ResourceId contains 'MICROSOFT.CONTAINERREGISTRY'\n| where OperationName == 'Push'\n| where $__timeFilter(Timestamp)\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Storage</h1>"
   }
  },
  {
   "title": "Container Registry Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERREGISTRY'\n| where MetricName == 'StorageUsed'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  }
 ]
}