apiVersion: 1
groups:
    - orgId: 1
      name: evaluation_group
      folder: online_store
      interval: 1m
      rules:
        - uid: 1
          title: Total Errors Count
          condition: B
          for: 5m
          data:
            - refId: A
              queryType: KQL
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: OBS360DataSource
              model:
                OpenAI: false
                clusterUri: ""
                database: openteldb
                datasource:
                    type: grafana-azure-data-explorer-datasource
                    uid: OBS360DataSource
                expression:
                    groupBy:
                        expressions: []
                        type: and
                    reduce:
                        expressions: []
                        type: and
                    where:
                        expressions: []
                        type: and
                intervalMs: 1000
                maxDataPoints: 43200
                pluginVersion: 5.1.1
                query: |-
                    OTELLogs
                    | where $__timeFilter(Timestamp)
                    | where Body !contains ("UNIQUE")
                    | where SeverityText == 'ERROR'
                    | where ResourceAttributes != "{}"
                    | extend ServiceName = tostring(ResourceAttributes.['service.name'])
                    | extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])
                    | extend CodeFunction = tostring(LogsAttributes.['code.function'])
                    | extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])
                    | count
                querySource: raw
                queryType: KQL
                rawMode: true
                refId: A
                resultFormat: table
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                      unloadEvaluator:
                        params:
                            - 0
                        type: lt
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: 10
          panelId: 4
          noDataState: NoData
          execErrState: Error
          annotations:
            __dashboardUid__: 10
            __panelId__: "4"
            description: Online Store Total Errors Count is above 0
            summary: Online Store has encountered an error(s), Please pay attention
          isPaused: false
          notification_settings:
            receiver: Contact Email Point
