{
 "title": "Kubernetes Service health",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Pods</h1>"
   }
  },
  {
   "title": "Running Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName == 'kube_pod_status_ready'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Unschedulable Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName == 'cluster_autoscaler_unschedulable_pods_count'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Cluster resources</h1>"
   }
  },
  {
   "title": "Cluster CPU usage percentages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'node_cpu_usage_percentage'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Cluster memory usage precentages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'node_memory_working_set_percentage'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Cluster CPU Cores allocatable",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'kube_node_status_allocatable_cpu_cores'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Cluster Memory bytes allocatable",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'kube_node_status_allocatable_memory_bytes'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">API Server</h1>"
   }
  },
  {
   "title": "API Server cpu usage percentages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'apiserver_cpu_usage_percentage'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "API Server memory usage percentages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'apiserver_memory_usage_percentage'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">ETCD</h1>"
   }
  },
  {
   "title": "ETCD cpu usage percentages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'etcd_cpu_usage_percentage'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "ETCD memory usage precentages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'etcd_memory_usage_percentage'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Cluster Autoscaler</h1>"
   }
  },
  {
   "title": "Autoscaler uneeded nodes count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'cluster_autoscaler_unneeded_nodes_count'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Autoscaler Safe to autoscale status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "observabilitydb",
     "expression": {
      "from": { "property": { "name": "DiagnosticMetrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS'\n| where MetricName contains 'cluster_autoscaler_cluster_safe_to_autoscale'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  }
 ]
}