{
 "title": "User Service Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "New Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| extend resource_json=parse_json(ResourceAttributes) \n| where resource_json['service.name'] == 'User Service'\n| where Body startswith \"Adding user\" \n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Removed Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| extend resource_json=parse_json(ResourceAttributes) \n| where resource_json['service.name'] == 'User Service'\n| where Body startswith \"Removing user\" \n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Updated Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| extend resource_json=parse_json(ResourceAttributes) \n| where resource_json['service.name'] == 'User Service'\n| where Body startswith \"Updating user\" \n| count",
     "querySource": "raw"
    }
   ]
  }
 ]
}