{
 "title": "ONLINE STORE STATUS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ONLINE STORE ERRORS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'ERROR'\n| where ResourceAttributes != \"{}\"\n| where TraceID != \"\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| summarize Errors = count() by TraceID, SpanID, Body\n| summarize TotalErrors = count()\n| project TotalErrors\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "TOTAL USER SERVICE #CALLS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where MetricName == 'user_srv_http_requests_total'\n| summarize arg_max(Timestamp, *) by MetricName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "ERROR DETAILS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'ERROR'\n| where ResourceAttributes != \"{}\"\n| where TraceID != \"\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| summarize Errors = count() by  TraceID,  Body, ServiceName\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "TOTAL ORDER SERVICE #CALLS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where MetricName == 'order_service_http_requests_total'\n| summarize arg_max(Timestamp, *) by MetricName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "SERVICE LATENCY",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELTraces\n| extend Latency = EndTime - StartTime\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| where not(ServiceName contains \"UI\")\n| summarize arg_max(Latency, *) by TraceID\n| project ServiceName, Latency, SpanID, TraceID\n| sort by Latency desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "TOTAL CART SERVICE #CALLS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where MetricName == 'cart_service_http_requests_total'\n| summarize arg_max(Timestamp, *) by MetricName",
     "querySource": "raw"
    }
   ]
  }
 ]
}